# This script dynamically generats a readme.md

output="$(cat autogen/readme_top.md)"

output="$output

## Current Emojis

| Emoji | Filename |
|:-----:|----------|
"

for f in $(ls emoji); do
	output="${output}| ![Emoji of ${f}](emoji/${f}) | \`${f}\` |
"
done

output="$output
> Readme autogenerated @ $(date)
"

echo "$output">readme.md
